### ISSUE TITLE
allow configurable external storage tracking options

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#211]
- [ ] `renku init --S --force` should disable external storage and untrack all files
- [ ] `renku storage local PATHS` and `renku storage external PATHS` to fine tune the options
- [x] `renku storage ls` will list files in an external storage
- [x] provide a `.renkuattributes` file with options for sizes etc.

**Comment by rokroskar** [comment]
If you are introducing a `storage` subcommand, then it seems like the first item on the list should also be done through it - besides, `init` is a misnomer for this since you are likely to be executing this command once the repo has already been developed a bit (i.e. not on an existing `git` repo that you are converting to a `renku` repo, which is the intent of the `init --force` afaik). 

Otherwise I like these options -- I might prefer to have a setting based on file size that I could set once and forget, rather than worrying about individual files.

**Comment by jirikuncar** [comment]
We indroduce `.renkuattributes` file where we can keep the settings for file size limits.

`renku storage init` is basically what is done in https://github.com/SwissDataScienceCenter/renku-python/blob/master/renku/api/repository.py#L191-L202.

**Comment by rokroskar** [comment]
This has been mostly addressed by #1235 #1234 and #1210 - can we close? /cc @mohammad-sdsc @Panaetius @emmjab

**Comment by Panaetius** [comment]
Closing since it's been addressed by the issues Rok mentioned
