### ISSUE TITLE
untangle LocalClient

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2254]
LocalClient is pretty much a horrible god object at the moment, being composed of several mixins that directly access properties of the other mixins, so they can only work if all the mixins are combined together.

We should replace this as much as possible with business layer logic, one class per concern/use-case, that don't directly depend on each other and can be used independently.

This entails moving functionality out of the LocalClient mixins to dedicated classes, changing the places it was used to use the new logic, refactor out common/global settings (like renku path) to an appropriate interface&implementation combo that can get injected and to also keep a close eye on if there's any logic in the mixin that is not actually business logic but might be domain logic or an external implementation detail and moving it to the appropriate place

- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3081
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3082
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3076
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3079
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3080
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3083
