### ISSUE TITLE
cli: better handle deleted inputs

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#237]
## Starting point
```console
$ renku run cmd ./source ./target
...
        deleted: source
...
```

## Question
1. ~Fail the whole command and restore everything;~
1. Commit file as deleted.

In the example above the source is committed as deleted as the `renku status` shows deleted inputs. We have to be very careful when re-building the graph not to mark the `target` file as out-dated since the `source` has been "modified" (deleted) in the same commit.

**NOTE we should not try to rely on file git renames done running `renku run mv old new`. The file renames can be supported later only via `git/renku mv`.**

## TODO list
* [x] handle file deletes and show deleted files in `renku status` (done #257);
* [ ] propose deletion of all outputs dependent on deleted inputs (pre-commit hook);
* [ ] support `rerun`/`update` when there is a deleted intermediate file;
* [ ] ~prevent deletion of input files (not created by `renku run`);~

**Comment by jirikuncar** [comment]
There would be steps with missing input files if you do manual move with `renku`. There is a way to track renames if they are done using `git mv` instead.

(I will change the example from `mv` to a `cmd`.)

**Comment by rokroskar** [comment]
@jirikuncar can you make a todo-list for this issue since one PR has already been merged? And maybe clarify the implementation decision?
