### ISSUE TITLE
Epic: Limit dataset files inside repo to being inside a datasets data directory

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2931]
At the moment, when a user adds a file to a dataset using `renku dataset add`, if the file is in the project already, it is just added as-is.
This can cause problems when importing the dataset, as on import all files are moved into the datadir in the target project, which can cause conflicts if a file with the same name is in the project and the dataset.

To illustrate:
```
$ renku dataset create test
$ echo "a" > myfile
$ renku dataset add test myfile  # myfile is added but not copied to data/test/
$ echo "b" > data/test/myfile
$ renku dataset add test data/test/myfile # second myfile is added to dataset as well, with different path

#in another project
$ renku dataset import --name new https://.../test
```
now all files from `test` will be imported to `data/new/`, but both`'myfile`s will be copied to that, and it's random if the content of `data/new/myfile` would be `a` or `b` now. `renku dataset ls-files new` would only show 1 file.

The reason is that we can't just copy `myfile` to the target project root, as a file might already be there, so we need to add it into the dataset directory, but that might also already contain a file of that name.

Probably the best solution to this problem is to always copy files into the datasets data directory when adding a file, and then only files in the data_dir (or external files) are allowed in a dataset. This way, there won't be any conflict when importing and it helps make the logic around importing easier. 

For big files/files in LFS, we would only want to copy the pointer file or symlink the file. And we need to keep some internal reference in the source project of where a file came from, so a user can `renku dataset update` in the source project and everything still works. Care should be taken that we don't double the disk usage in this case, as that might break interactive sessions.

Projects that import the dataset wouldn't know about this link and just have the files inside the datasets datadir.

Result of the design discussion:
- User can set datadir on a per-dataset level (default: `data/<dataset-name>`)
- Add git commit hook to automatically detect and add files in a datasets datadir (prompt users before doing this).
- `renku dataset unlink` should remove files from the datadir, not just the metadata
- Default action when adding a file (in the repo, from outside the data dir) to a dataset is to move the file there, prompting the user to confirm
  - Add flags `--move` (to move without confirmation), `--copy` (to copy the file instead of moving), `--ln` (to create a symlink instead)

**Features**

- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/2977
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/2978
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/2979
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/2980
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/2981
- [x] https://github.com/SwissDataScienceCenter/renku-python/issues/3034
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3035

~~Check with ORDES if this approach is ok.~~

~~Break up into multiple stories (internal renku pointer file?), create a design for this.~~

~~Stories could be:~~
~~- adding copy and/or move functionality for `renku dataset add`, checking for conflicts~~
~~- improving `renku dataset update` to automatically pick up files in a datasets data-directory~~
~~- changing import logic to only import files inside a datasets datadir~~
~~- Figuring out a sort of renku pointer-file that we could use instead of copy/move to not have duplicate data~~
~~- `renku doctor` command to fix preexisting datasets~~
~~- (Maybe: allow defining a datasets data-directory on a per-dataset level instead of on a per-project level as it is now)~~

**Comment by Panaetius** [comment]
Check with ORDES if this approach is ok.

Break up into multiple stories (internal renku pointer file?), create a design for this
