### ISSUE TITLE
Epic: core-service scalability

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#3006]
core-service currently does not support scaling and is a single point of failure. If we ever experience heavy load on it, it can be a serious bottleneck.

As such, we should add support for scaling up the core-service, preferably with auto-scaling

- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3039
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3007
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3008
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3009
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3010
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3011
- [ ] https://github.com/SwissDataScienceCenter/renku-python/issues/3012

**Comment by olevski** [comment]
This is one way we could achieve this:
- create an operator that would handle two resources BlankCache and HydratedCache
- BlankCache is an instance of the core service that has essentially an empty cache folder
- HydratedCache is a BlankCache where `git clone` has been done and for which there is a k8s Service
- The original user facing core service then does the following on each request:
  1. Create HydratedCache for the specific project, user and branch (if the cache already exists all is good k8s does not do anything if you "recreate" the exact same manifest)
  2. Send the request to the HydratedCache (using the k8s service)
  3. Wait for a response form the HydratedCache
  4. Forward the HydratedCache response to the client

```mermaid
flowchart TB
    A[Client] --> |JSON RPC<br>request| B[[Core service<br>JSON RPC API]]
    B --> C[Create HydratedCache]
    B -.-> |JSON RPC<br>response| A
    C --> D{HydratedCache<br>exists?}
    D --> |No| E{Is there a free<br>BlankCache?}
    D --> |Yes| G
    E --> |No| F[Create new Caches<br>or evict existing]
    H --> |git clone<br>create k8s Service| H
    F --> H
    E --> |Yes| H[Hydrate BlankCache]
    H --> G[Forward request<br>to HydratedCache]
    G --> I[[HydratedCache]]
    I -.->|Forward response<br>through core service| B 
```

**Comment by rokroskar** [comment]
I'm not sure I understand how this enables zero-downtime upgrades. What will happen with the `HydratedCache` when we roll out a new version of the core service?
