### ISSUE TITLE
Implement core service scaling

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-python#3104]
Based on findings described in #3094:

Tasks:
- [ ] Finish or replace changes in #3094 
- [ ] [Core service scaling: implement horizontal pod autoscaler](https://github.com/SwissDataScienceCenter/renku-python/issues/3102)
- [ ] [Core service scaling: separate RQ workers](https://github.com/SwissDataScienceCenter/renku-python/issues/3101)
- [ ] [Core service scaling: handle error cases and interruptions](https://github.com/SwissDataScienceCenter/renku-python/issues/3103)
- [ ] [Gateway: do not strip sticky session cookie](https://github.com/SwissDataScienceCenter/renku-gateway/issues/585)
- [ ] [UI server: do not strip sticky session cookie](https://github.com/SwissDataScienceCenter/renku-ui/issues/2018)
