### ISSUE TITLE
Renku metadata cleanup and quality-of-life improvement

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#621]
As dataset metadata is growing more important, we should make sure that metadata is actually set on datasets.

We should:
- [ ] Prompt the user to enter all mandatory values when creating a new dataset
- [ ] Have a more human-friendly way of editing metadata
- [ ] Infer metadata whenever possible and offer it as default. For instance `creator` can be set to the current git user and prompted for like `Enter creator name(John Doe): `
- [ ] Provide an easy way to migrate datasets without metadata
